name: transit
version: 0.8.3
author: Clean Team <clean@vacuumlabs.com>
description: Transit for Dart
homepage: https://github.com/cleandart/transit-dart
dependencies:
  crypto: '>=0.9.0'
  msgpack2: '^2.0.0'
dev_dependencies:
  test:
